name: GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg

          base: header, activity, community, repositories, metadata

          plugin_traffic: yes

          plugin_languages: yes
          plugin_languages_ignored: Jupyter Notebook, CSS, HTML, Vue, Less, ASL
          plugin_languages_sections: most-used, recently-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_days: sunday,monday,tuesday,wednesday,thursday,friday,saturday

          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: stars

          plugin_achievements: no
          plugin_achievements_display: compact
          plugin_achievements_limit: 5
          plugin_achievements_threshold: C

          plugin_lines: yes
